#!/bin/sh

# strip svk and git-svn noise, retaining tags
git filter-branch --tag-name-filter cat --msg-filter "git svn-abandon-msg-filter" -- --all

# remove the backup refs
git for-each-ref --format='%(refname)' refs/original/ refs/remotes/svn/ | while read ref; do
    git update-ref -d "$ref"
done

# ditch all pre-conversion objects forcefully
git reflog expire --all --expire=now
git gc --aggressive

git prune
git fsck --full
